project:
  type: website
  output-dir: docs

extensions:
  - jmgirard/embedpdf

website:
  title: "shruthis_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd  # <-- add this
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



