<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shruthi Suresh">
<meta name="dcterms.date" content="2025-05-07">

<title>Homework 1 – shruthis_website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>



<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">shruthis_website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shruthi Suresh </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>In their 2007 study published in the American Economic Review, Dean Karlan (Yale) and John List (University of Chicago) conducted a large-scale natural field experiment to test how different types of fundraising letters affect donation behavior.</p>
<p>The experiment involved over 50,000 previous donors to a politically progressive nonprofit organization. These donors were randomly assigned to receive one of several versions of a fundraising letter via direct mail. The goal was to understand whether matching grant offers which promise to “match” a donor’s gift in order to encourage more people to donate, and whether the size or structure of the match affects donor behavior.</p>
<p>Key Experimental Groups:</p>
<ol type="1">
<li><p>Control Group: Received a standard fundraising letter with no mention of a match.</p></li>
<li><p>Treatment Groups: Received a letter that mentioned a matching grant. These were further split into subgroups based on:</p></li>
<li><p>Match Ratio: $1:$1, $2:$1, or $3:$1 (i.e., for every dollar donated, the donor’s gift would be matched by $1, $2, or $3).</p></li>
<li><p>Maximum Match Amount: The match offer was capped at $25,000, $50,000, $100,000, or not stated at all.</p></li>
<li><p>Suggested Donation Amount: The letter included examples of donation amounts equal to, 1.25 times, or 1.5 times the recipient’s highest previous contribution.</p></li>
</ol>
<p>Each version of the letter was randomly assigned to ensure that any differences in responses could be attributed to the content of the letter rather than who received it.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<div id="62d03bfd" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace with your file path</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first few row</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">treatment</th>
<th data-quarto-table-cell-role="th">control</th>
<th data-quarto-table-cell-role="th">ratio</th>
<th data-quarto-table-cell-role="th">ratio2</th>
<th data-quarto-table-cell-role="th">ratio3</th>
<th data-quarto-table-cell-role="th">size</th>
<th data-quarto-table-cell-role="th">size25</th>
<th data-quarto-table-cell-role="th">size50</th>
<th data-quarto-table-cell-role="th">size100</th>
<th data-quarto-table-cell-role="th">sizeno</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">redcty</th>
<th data-quarto-table-cell-role="th">bluecty</th>
<th data-quarto-table-cell-role="th">pwhite</th>
<th data-quarto-table-cell-role="th">pblack</th>
<th data-quarto-table-cell-role="th">page18_39</th>
<th data-quarto-table-cell-role="th">ave_hh_sz</th>
<th data-quarto-table-cell-role="th">median_hhincome</th>
<th data-quarto-table-cell-role="th">powner</th>
<th data-quarto-table-cell-role="th">psch_atlstba</th>
<th data-quarto-table-cell-role="th">pop_propurban</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>1</td>
<td>Control</td>
<td>0</td>
<td>0</td>
<td>Control</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0.0</td>
<td>1.0</td>
<td>0.446493</td>
<td>0.527769</td>
<td>0.317591</td>
<td>2.10</td>
<td>28517.0</td>
<td>0.499807</td>
<td>0.324528</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0</td>
<td>1</td>
<td>Control</td>
<td>0</td>
<td>0</td>
<td>Control</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>1.0</td>
<td>0.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>$100,000</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>...</td>
<td>0.0</td>
<td>1.0</td>
<td>0.935706</td>
<td>0.011948</td>
<td>0.276128</td>
<td>2.48</td>
<td>51175.0</td>
<td>0.721941</td>
<td>0.192668</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Unstated</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>...</td>
<td>1.0</td>
<td>0.0</td>
<td>0.888331</td>
<td>0.010760</td>
<td>0.279412</td>
<td>2.65</td>
<td>79269.0</td>
<td>0.920431</td>
<td>0.412142</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>$50,000</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0.0</td>
<td>1.0</td>
<td>0.759014</td>
<td>0.127421</td>
<td>0.442389</td>
<td>1.85</td>
<td>40908.0</td>
<td>0.416072</td>
<td>0.439965</td>
<td>1.0</td>
</tr>
</tbody>
</table>

<p>5 rows × 51 columns</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<div id="a0a4286c" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Choose pre-treatment variables to test</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>test_vars <span class="op">=</span> [<span class="st">'mrm2'</span>, <span class="st">'hpa'</span>, <span class="st">'freq'</span>, <span class="st">'years'</span>]</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Initialize list to store results</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> []</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Loop through each variable</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> var <span class="kw">in</span> test_vars:</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Drop missing values for each test</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    temp_df <span class="op">=</span> df[[<span class="st">'treatment'</span>, var]].dropna()</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Separate treatment and control group values</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    treated <span class="op">=</span> temp_df[temp_df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][var]</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    control <span class="op">=</span> temp_df[temp_df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][var]</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- T-Test ---</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    t_stat, p_val_ttest <span class="op">=</span> stats.ttest_ind(treated, control, equal_var<span class="op">=</span><span class="va">False</span>)  <span class="co"># Welch's t-test</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- Linear Regression ---</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> sm.add_constant(temp_df[<span class="st">'treatment'</span>])  <span class="co"># Add intercept</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> temp_df[var]</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> sm.OLS(y, X).fit()</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get treatment coefficient and p-value</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    coef <span class="op">=</span> model.params[<span class="st">'treatment'</span>]</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    p_val_reg <span class="op">=</span> model.pvalues[<span class="st">'treatment'</span>]</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store results</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    results.append({</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Variable'</span>: var,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">'T-test p-value'</span>: <span class="bu">round</span>(p_val_ttest, <span class="dv">4</span>),</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Regression Coef. (Treatment)'</span>: <span class="bu">round</span>(coef, <span class="dv">4</span>),</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Regression p-value'</span>: <span class="bu">round</span>(p_val_reg, <span class="dv">4</span>)</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Convert to DataFrame and display</span></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame(results)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Variable  T-test p-value  Regression Coef. (Treatment)  Regression p-value
0     mrm2          0.9049                        0.0137              0.9049
1      hpa          0.3318                        0.6371              0.3451
2     freq          0.9117                       -0.0120              0.9117
3    years          0.2753                       -0.0575              0.2700</code></pre>
</div>
</div>
<p>Conclusion:</p>
<ol type="1">
<li><p>All p-values are well above 0.05:</p>
<p>A. This means we fail to reject the null hypothesis in every case.</p>
<p>B. There is no evidence that the treatment and control groups differ on these characteristics.</p></li>
<li><p>T-test and regression results match exactly:</p>
<p>A. Confirms that both statistical methods are working as expected for comparing group means.</p>
<p>B. Demonstrates strong understanding of the equivalence between t-tests and simple OLS regressions.</p></li>
<li><p>Randomization appears successful:</p>
<p>A. The balance across these variables suggests that the treatment assignment was indeed random.</p>
<p>B. This supports the internal validity of the experiment: any observed differences in donation behavior can reasonably be attributed to the treatment, not to pre-existing differences.</p></li>
</ol>
<p>The treatment and control groups were statistically indistinguishable across key baseline variables. This is strong evidence that the randomization mechanism worked properly, ensuring that subsequent comparisons of outcomes (like giving behavior) are valid and free from selection bias.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<div id="d0930cc6" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">### Charitable Contribution Made</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the donation rates for control (0) and treatment (1)</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>donation_rates <span class="op">=</span> df.groupby(<span class="st">'treatment'</span>)[<span class="st">'gave'</span>].mean()</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">4</span>))</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> plt.bar([<span class="st">'Control'</span>, <span class="st">'Treatment'</span>], donation_rates, color<span class="op">=</span><span class="st">'orange'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Proportion of People Who Donated'</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Donation Rate'</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="fl">0.03</span>)  <span class="co"># Zoom in on small values</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Annotate the bars with exact values</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar <span class="kw">in</span> bars:</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> bar.get_height()</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    plt.text(bar.get_x() <span class="op">+</span> bar.get_width()<span class="op">/</span><span class="dv">2</span>, height <span class="op">+</span> <span class="fl">0.0005</span>, <span class="ss">f'</span><span class="sc">{</span>height<span class="sc">:.4f}</span><span class="ss">'</span>, </span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-4-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="54702cee" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Clean the data (remove any missing values in relevant columns)</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df[[<span class="st">'treatment'</span>, <span class="st">'gave'</span>]].dropna()</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Separate treatment and control groups</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>gave_treated <span class="op">=</span> df_clean[df_clean[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>gave_control <span class="op">=</span> df_clean[df_clean[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'gave'</span>]</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Run a t-test (Welch’s t-test)</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>t_stat, p_val_ttest <span class="op">=</span> stats.ttest_ind(gave_treated, gave_control, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Run a linear regression: gave ~ treatment</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(df_clean[<span class="st">'treatment'</span>])  <span class="co"># Add constant (intercept)</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_clean[<span class="st">'gave'</span>]</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(y, X).fit()</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Print Results</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== T-test ==="</span>)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>p_val_ttest<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== Linear Regression ==="</span>)</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Treatment Coefficient: </span><span class="sc">{</span>model<span class="sc">.</span>params[<span class="st">'treatment'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>model<span class="sc">.</span>pvalues[<span class="st">'treatment'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Full Summary:"</span>)</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)
=== T-test ===
T-statistic: 3.2095
P-value: 0.0013

=== Linear Regression ===
Treatment Coefficient: 0.0042
P-value: 0.0019

Full Summary:
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   gave   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     9.618
Date:                Wed, 23 Apr 2025   Prob (F-statistic):            0.00193
Time:                        17:49:32   Log-Likelihood:                 26630.
No. Observations:               50083   AIC:                        -5.326e+04
Df Residuals:                   50081   BIC:                        -5.324e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0179      0.001     16.225      0.000       0.016       0.020
treatment      0.0042      0.001      3.101      0.002       0.002       0.007
==============================================================================
Omnibus:                    59814.280   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          4317152.727
Skew:                           6.740   Prob(JB):                         0.00
Kurtosis:                      46.440   Cond. No.                         3.23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
</div>
<p>Interpretation:</p>
<ol type="1">
<li><p>This analysis shows that people who received a fundraising letter mentioning a matching donation offer were significantly more likely to donate than those who received a standard letter.</p></li>
<li><p>Although the increase in response was small in absolute terms (about 0.42 percentage points), it is statistically significant — meaning it’s very unlikely to be due to chance.</p></li>
<li><p>It suggests that people are more likely to act charitably when they believe their actions are amplified. The match offer may make them feel their contribution has greater impact — which taps into psychological motivations like making a difference or being part of something larger.</p></li>
</ol>
<div id="ce466df4" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Clean the data (drop rows with missing values)</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df[[<span class="st">'treatment'</span>, <span class="st">'gave'</span>]].dropna()</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Set up the regression variables</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(df_clean[<span class="st">'treatment'</span>])  <span class="co"># Add constant (intercept)</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_clean[<span class="st">'gave'</span>]</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Run the Probit model</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>probit_model <span class="op">=</span> sm.Probit(y, X).fit()</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Print the results</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(probit_model.summary())</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Extract key statistics (optional)</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>coef <span class="op">=</span> probit_model.params[<span class="st">'treatment'</span>]</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> probit_model.pvalues[<span class="st">'treatment'</span>]</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Treatment Coefficient: </span><span class="sc">{</span>coef<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)
Optimization terminated successfully.
         Current function value: 0.100443
         Iterations 7</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Probit Regression Results                           
==============================================================================
Dep. Variable:                   gave   No. Observations:                50083
Model:                         Probit   Df Residuals:                    50081
Method:                           MLE   Df Model:                            1
Date:                Wed, 23 Apr 2025   Pseudo R-squ.:               0.0009783
Time:                        17:49:44   Log-Likelihood:                -5030.5
converged:                       True   LL-Null:                       -5035.4
Covariance Type:            nonrobust   LLR p-value:                  0.001696
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.1001      0.023    -90.073      0.000      -2.146      -2.054
treatment      0.0868      0.028      3.113      0.002       0.032       0.141
==============================================================================

Treatment Coefficient: 0.0868
P-value: 0.0019</code></pre>
</div>
</div>
<p>Conclusion and comparison with Table 3 (column 1)</p>
<p>In this experiment, we tested whether offering to match a person’s donation increased their likelihood of donating. Using a probit regression, we found that individuals who received a matching offer were significantly more likely to donate compared to those who didn’t. Although the overall increase in donation probability was small (about 0.4 percentage points), it was statistically significant, meaning it’s unlikely to be due to chance.</p>
<p>This suggests that even subtle changes in how donation requests are framed like offering to match the gift, can meaningfully influence people’s behavior.</p>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<div id="d0a73695" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Filter to treatment group with valid numeric match ratios</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>df_ratio <span class="op">=</span> df[(df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'ratio'</span>].isin([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]))].copy()</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Extract 'gave' values for each match ratio</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>gave_1to1 <span class="op">=</span> df_ratio[df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>gave_2to1 <span class="op">=</span> df_ratio[df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>][<span class="st">'gave'</span>]</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>gave_3to1 <span class="op">=</span> df_ratio[df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>][<span class="st">'gave'</span>]</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Perform t-tests</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>t_21_vs_11, p_21_vs_11 <span class="op">=</span> ttest_ind(gave_2to1, gave_1to1, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>t_31_vs_11, p_31_vs_11 <span class="op">=</span> ttest_ind(gave_3to1, gave_1to1, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>t_31_vs_21, p_31_vs_21 <span class="op">=</span> ttest_ind(gave_3to1, gave_2to1, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Print results</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== T-Test Results by Match Ratio ==="</span>)</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2:1 vs 1:1 p-value: </span><span class="sc">{</span>p_21_vs_11<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 vs 1:1 p-value: </span><span class="sc">{</span>p_31_vs_11<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 vs 2:1 p-value: </span><span class="sc">{</span>p_31_vs_21<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)
=== T-Test Results by Match Ratio ===
2:1 vs 1:1 p-value: 0.3345
3:1 vs 1:1 p-value: 0.3101
3:1 vs 2:1 p-value: 0.9600</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
</div>
<p>Conclusion:</p>
<ol type="1">
<li><p>We tested whether increasing the match ratio (from 1:1 to 2:1 or 3:1) made people more likely to donate. The results show that none of the differences are statistically significant — the p-values are all well above 0.05.</p></li>
<li><p>Even though the match ratio increased, it did not increase the probability that someone would donate in a statistically meaningful way. This is similar to what the author suggested in Page 8:</p></li>
</ol>
<p>“Figures suggest that larger match ratios (i.e., $3:$1 and $2:$1) relative to a smaller match ratio ($1:$1) had no additional impact.”</p>
<div id="a1dc750a" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Filter to treatment group with valid match ratios</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>df_ratio <span class="op">=</span> df[(df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'ratio'</span>].isin([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]))].copy()</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Create dummy variables</span></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>df_ratio[<span class="st">'ratio1'</span>] <span class="op">=</span> (df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>).astype(<span class="bu">int</span>)</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>df_ratio[<span class="st">'ratio2'</span>] <span class="op">=</span> (df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>).astype(<span class="bu">int</span>)</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>df_ratio[<span class="st">'ratio3'</span>] <span class="op">=</span> (df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>).astype(<span class="bu">int</span>)</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Run regression with 1:1 match as baseline (omit ratio1)</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'gave ~ ratio2 + ratio3'</span>, data<span class="op">=</span>df_ratio).fit()</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Print the summary</span></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   gave   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.6454
Date:                Wed, 23 Apr 2025   Prob (F-statistic):              0.524
Time:                        17:50:08   Log-Likelihood:                 16688.
No. Observations:               33396   AIC:                        -3.337e+04
Df Residuals:                   33393   BIC:                        -3.334e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0207      0.001     14.912      0.000       0.018       0.023
ratio2         0.0019      0.002      0.958      0.338      -0.002       0.006
ratio3         0.0020      0.002      1.008      0.313      -0.002       0.006
==============================================================================
Omnibus:                    38963.957   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2506478.937
Skew:                           6.511   Prob(JB):                         0.00
Kurtosis:                      43.394   Cond. No.                         3.73
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Conclusion:</p>
<ol type="1">
<li><p>Linear regression assumes a continuous outcome, but donation (gave) is binary (0 or 1). This can lead to invalid predicted values outside the [0, 1] range and doesn’t capture how people make yes/no decisions. A Probit or Logit model would be more appropriate, as they are designed for binary outcomes and model probabilities directly.</p></li>
<li><p>Interpretation:</p>
<p>A. People offered a 2:1 or 3:1 match were slightly more likely to donate than those offered a 1:1 match, but:</p>
<p>B. These differences are very small (~0.2 percentage points) and not statistically significant.</p>
<p>C. The p-values (0.338 and 0.313) are well above the 0.05 threshold, meaning we can’t rule out that these differences happened by chance.</p></li>
</ol>
<div id="716f0565" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Filter to only treatment group with valid match ratios</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>df_ratio <span class="op">=</span> df[(df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'ratio'</span>].isin([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]))].copy()</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Compute donation rates directly</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>gave_1to1_rate <span class="op">=</span> df_ratio[df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>gave_2to1_rate <span class="op">=</span> df_ratio[df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>gave_3to1_rate <span class="op">=</span> df_ratio[df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Compute direct differences in response rates</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>diff_21_11_direct <span class="op">=</span> gave_2to1_rate <span class="op">-</span> gave_1to1_rate</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>diff_31_21_direct <span class="op">=</span> gave_3to1_rate <span class="op">-</span> gave_2to1_rate</span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Re-run regression to get coefficient-based differences</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>df_ratio[<span class="st">'ratio2'</span>] <span class="op">=</span> (df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>).astype(<span class="bu">int</span>)</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>df_ratio[<span class="st">'ratio3'</span>] <span class="op">=</span> (df_ratio[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>).astype(<span class="bu">int</span>)</span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'gave ~ ratio2 + ratio3'</span>, data<span class="op">=</span>df_ratio).fit()</span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Extract regression-based differences</span></span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>coef_21 <span class="op">=</span> model.params[<span class="st">'ratio2'</span>]</span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a>coef_31 <span class="op">=</span> model.params[<span class="st">'ratio3'</span>]</span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>diff_31_21_coef <span class="op">=</span> coef_31 <span class="op">-</span> coef_21</span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 7: Display all results</span></span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== Direct Differences from Data ==="</span>)</span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2:1 vs 1:1 match: </span><span class="sc">{</span>diff_21_11_direct<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 vs 2:1 match: </span><span class="sc">{</span>diff_31_21_direct<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb42-42"><a href="#cb42-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-43"><a href="#cb42-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">=== Differences from Regression Coefficients ==="</span>)</span>
<span id="cb42-44"><a href="#cb42-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2:1 vs 1:1 (coef): </span><span class="sc">{</span>coef_21<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb42-45"><a href="#cb42-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 vs 2:1 (coef diff): </span><span class="sc">{</span>diff_31_21_coef<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== Direct Differences from Data ===
2:1 vs 1:1 match: 0.0019
3:1 vs 2:1 match: 0.0001

=== Differences from Regression Coefficients ===
2:1 vs 1:1 (coef): 0.0019
3:1 vs 2:1 (coef diff): 0.0001</code></pre>
</div>
</div>
<p>Conclusion: 1. Moving from a 1:1 to 2:1 match increased donations by 0.19 percentage points, but it’s very small and not statistically significant.</p>
<pre><code>2. Going from 2:1 to 3:1 added almost nothing (+0.01 percentage points).

3. Both the data and the regression tell the same story.</code></pre>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<div id="db656bad" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Drop missing values in 'amount' column</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>df_amount <span class="op">=</span> df[[<span class="st">'treatment'</span>, <span class="st">'amount'</span>]].dropna()</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: T-test between treatment and control groups on amount donated</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>amount_treatment <span class="op">=</span> df_amount[df_amount[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>]</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>amount_control <span class="op">=</span> df_amount[df_amount[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>]</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>t_stat, p_val <span class="op">=</span> ttest_ind(amount_treatment, amount_control, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Linear regression of donation amount on treatment</span></span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'amount ~ treatment'</span>, data<span class="op">=</span>df_amount).fit()</span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Display results</span></span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== T-test Results ==="</span>)</span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>p_val<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">=== Regression Summary ==="</span>)</span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== T-test Results ===
T-statistic: 1.9183
P-value: 0.0551

=== Regression Summary ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 amount   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     3.461
Date:                Wed, 23 Apr 2025   Prob (F-statistic):             0.0628
Time:                        17:50:32   Log-Likelihood:            -1.7946e+05
No. Observations:               50083   AIC:                         3.589e+05
Df Residuals:                   50081   BIC:                         3.589e+05
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.8133      0.067     12.063      0.000       0.681       0.945
treatment      0.1536      0.083      1.861      0.063      -0.008       0.315
==============================================================================
Omnibus:                    96861.113   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        240735713.635
Skew:                          15.297   Prob(JB):                         0.00
Kurtosis:                     341.269   Cond. No.                         3.23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Learnings:</p>
<pre><code>1. We analyzed whether receiving a matching donation offer affected how much people gave. On average, people in the treatment group gave $0.15 more, but the difference was only marginally significant (p ≈ 0.06).

2. This suggests that matched donation offers may slightly increase donation size, but the effect is not strong enough to confidently rule out chance. The main impact of the match appears to be on whether people give, not how much they give.</code></pre>
<div id="c69406e9" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to only those who donated (i.e., amount &gt; 0 or gave == 1)</span></span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>df_positive <span class="op">=</span> df[(df[<span class="st">'gave'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'amount'</span>] <span class="op">&gt;</span> <span class="dv">0</span>)].copy()</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression of donation amount on treatment status</span></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>model_positive <span class="op">=</span> smf.ols(<span class="st">'amount ~ treatment'</span>, data<span class="op">=</span>df_positive).fit()</span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the results</span></span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_positive.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 amount   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.3374
Date:                Wed, 23 Apr 2025   Prob (F-statistic):              0.561
Time:                        17:50:44   Log-Likelihood:                -5326.8
No. Observations:                1034   AIC:                         1.066e+04
Df Residuals:                    1032   BIC:                         1.067e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     45.5403      2.423     18.792      0.000      40.785      50.296
treatment     -1.6684      2.872     -0.581      0.561      -7.305       3.968
==============================================================================
Omnibus:                      587.258   Durbin-Watson:                   2.031
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5623.279
Skew:                           2.464   Prob(JB):                         0.00
Kurtosis:                      13.307   Cond. No.                         3.49
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Conclusion :</p>
<pre><code>1. Among people who donated, those in the treatment group gave $1.67 less than those in the control group, but this difference was not statistically significant (p = 0.561). This suggests that while matched donations may influence whether someone gives, they do not significantly affect the size of the donation among those who already choose to give.

2. The treatment coefficient has a causal interpretation within the donor subgroup, due to random assignment, but cannot be generalized to the full sample because it conditions on a post-treatment outcome.</code></pre>
<div id="7008f877" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">'karlan_list_2007.dta'</span>)</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Filter to only donors</span></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>df_donors <span class="op">=</span> df[(df[<span class="st">'gave'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'amount'</span>] <span class="op">&gt;</span> <span class="dv">0</span>)]</span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Split by treatment group</span></span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a>treatment_donors <span class="op">=</span> df_donors[df_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>]</span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a>control_donors <span class="op">=</span> df_donors[df_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>]</span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-23"><a href="#cb67-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Compute means</span></span>
<span id="cb67-24"><a href="#cb67-24" aria-hidden="true" tabindex="-1"></a>mean_treatment <span class="op">=</span> treatment_donors.mean()</span>
<span id="cb67-25"><a href="#cb67-25" aria-hidden="true" tabindex="-1"></a>mean_control <span class="op">=</span> control_donors.mean()</span>
<span id="cb67-26"><a href="#cb67-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-27"><a href="#cb67-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Plot histograms</span></span>
<span id="cb67-28"><a href="#cb67-28" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>))</span>
<span id="cb67-29"><a href="#cb67-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-30"><a href="#cb67-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Control group histogram</span></span>
<span id="cb67-31"><a href="#cb67-31" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb67-32"><a href="#cb67-32" aria-hidden="true" tabindex="-1"></a>plt.hist(control_donors, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'skyblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb67-33"><a href="#cb67-33" aria-hidden="true" tabindex="-1"></a>plt.axvline(mean_control, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb67-34"><a href="#cb67-34" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Control Group: Donation Amounts'</span>)</span>
<span id="cb67-35"><a href="#cb67-35" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Donation Amount ($)'</span>)</span>
<span id="cb67-36"><a href="#cb67-36" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Donors'</span>)</span>
<span id="cb67-37"><a href="#cb67-37" aria-hidden="true" tabindex="-1"></a>plt.text(mean_control <span class="op">+</span> <span class="dv">1</span>, plt.ylim()[<span class="dv">1</span>]<span class="op">*</span><span class="fl">0.9</span>, <span class="ss">f'Mean = $</span><span class="sc">{</span>mean_control<span class="sc">:.2f}</span><span class="ss">'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb67-38"><a href="#cb67-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-39"><a href="#cb67-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Treatment group histogram</span></span>
<span id="cb67-40"><a href="#cb67-40" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb67-41"><a href="#cb67-41" aria-hidden="true" tabindex="-1"></a>plt.hist(treatment_donors, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'lightgreen'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb67-42"><a href="#cb67-42" aria-hidden="true" tabindex="-1"></a>plt.axvline(mean_treatment, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb67-43"><a href="#cb67-43" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Treatment Group: Donation Amounts'</span>)</span>
<span id="cb67-44"><a href="#cb67-44" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Donation Amount ($)'</span>)</span>
<span id="cb67-45"><a href="#cb67-45" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Donors'</span>)</span>
<span id="cb67-46"><a href="#cb67-46" aria-hidden="true" tabindex="-1"></a>plt.text(mean_treatment <span class="op">+</span> <span class="dv">1</span>, plt.ylim()[<span class="dv">1</span>]<span class="op">*</span><span class="fl">0.9</span>, <span class="ss">f'Mean = $</span><span class="sc">{</span>mean_treatment<span class="sc">:.2f}</span><span class="ss">'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb67-47"><a href="#cb67-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-48"><a href="#cb67-48" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb67-49"><a href="#cb67-49" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-12-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<div id="2b01a85e" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Define true probabilities</span></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>p_control <span class="op">=</span> <span class="fl">0.018</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>p_treatment <span class="op">=</span> <span class="fl">0.022</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Simulate the data</span></span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 100,000 draws for control group</span></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a>control_draws <span class="op">=</span> np.random.binomial(n<span class="op">=</span><span class="dv">1</span>, p<span class="op">=</span>p_control, size<span class="op">=</span><span class="dv">100000</span>)</span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 10,000 draws for treatment group</span></span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a>treatment_draws <span class="op">=</span> np.random.binomial(n<span class="op">=</span><span class="dv">1</span>, p<span class="op">=</span>p_treatment, size<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Randomly sample 10,000 control values to match treatment size</span></span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a>control_sample <span class="op">=</span> np.random.choice(control_draws, size<span class="op">=</span><span class="dv">10000</span>, replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Calculate pointwise differences</span></span>
<span id="cb74-30"><a href="#cb74-30" aria-hidden="true" tabindex="-1"></a>differences <span class="op">=</span> treatment_draws <span class="op">-</span> control_sample</span>
<span id="cb74-31"><a href="#cb74-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-32"><a href="#cb74-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Compute cumulative average of differences</span></span>
<span id="cb74-33"><a href="#cb74-33" aria-hidden="true" tabindex="-1"></a>cumulative_avg <span class="op">=</span> np.cumsum(differences) <span class="op">/</span> np.arange(<span class="dv">1</span>, <span class="dv">10001</span>)</span>
<span id="cb74-34"><a href="#cb74-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-35"><a href="#cb74-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Plot</span></span>
<span id="cb74-36"><a href="#cb74-36" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb74-37"><a href="#cb74-37" aria-hidden="true" tabindex="-1"></a>plt.plot(cumulative_avg, label<span class="op">=</span><span class="st">'Cumulative Average of Differences'</span>)</span>
<span id="cb74-38"><a href="#cb74-38" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span>(p_treatment <span class="op">-</span> p_control), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'True Difference (0.004)'</span>)</span>
<span id="cb74-39"><a href="#cb74-39" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Law of Large Numbers: Cumulative Average of Simulated Differences'</span>)</span>
<span id="cb74-40"><a href="#cb74-40" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Simulations'</span>)</span>
<span id="cb74-41"><a href="#cb74-41" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cumulative Average Difference'</span>)</span>
<span id="cb74-42"><a href="#cb74-42" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb74-43"><a href="#cb74-43" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb74-44"><a href="#cb74-44" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb74-45"><a href="#cb74-45" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-13-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Conclusion:</p>
<p>The plot confirms that as the number of simulated trials increases, the average difference in donation likelihood between treatment and control groups converges to the true difference of 0.004, illustrating the Law of Large Numbers.</p>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<div id="135267b5" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install pandas</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install matplotlib</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install statsmodels</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Parameters</span></span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>p_control <span class="op">=</span> <span class="fl">0.018</span></span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>p_treatment <span class="op">=</span> <span class="fl">0.022</span></span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>]</span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a>n_simulations <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb80-18"><a href="#cb80-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-19"><a href="#cb80-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Set up plots</span></span>
<span id="cb80-20"><a href="#cb80-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb80-21"><a href="#cb80-21" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb80-22"><a href="#cb80-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-23"><a href="#cb80-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Run simulations for each sample size</span></span>
<span id="cb80-24"><a href="#cb80-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> idx, size <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes):</span>
<span id="cb80-25"><a href="#cb80-25" aria-hidden="true" tabindex="-1"></a>    avg_differences <span class="op">=</span> []</span>
<span id="cb80-26"><a href="#cb80-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-27"><a href="#cb80-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_simulations):</span>
<span id="cb80-28"><a href="#cb80-28" aria-hidden="true" tabindex="-1"></a>        control_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_control, size)</span>
<span id="cb80-29"><a href="#cb80-29" aria-hidden="true" tabindex="-1"></a>        treatment_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_treatment, size)</span>
<span id="cb80-30"><a href="#cb80-30" aria-hidden="true" tabindex="-1"></a>        diff <span class="op">=</span> treatment_sample.mean() <span class="op">-</span> control_sample.mean()</span>
<span id="cb80-31"><a href="#cb80-31" aria-hidden="true" tabindex="-1"></a>        avg_differences.append(diff)</span>
<span id="cb80-32"><a href="#cb80-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-33"><a href="#cb80-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Step 4: Plot histogram</span></span>
<span id="cb80-34"><a href="#cb80-34" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[idx]</span>
<span id="cb80-35"><a href="#cb80-35" aria-hidden="true" tabindex="-1"></a>    ax.hist(avg_differences, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'lightgray'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb80-36"><a href="#cb80-36" aria-hidden="true" tabindex="-1"></a>    ax.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Zero'</span>)</span>
<span id="cb80-37"><a href="#cb80-37" aria-hidden="true" tabindex="-1"></a>    ax.axvline(<span class="fl">0.004</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'True Mean Diff (0.004)'</span>)</span>
<span id="cb80-38"><a href="#cb80-38" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"Sample Size: </span><span class="sc">{</span>size<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb80-39"><a href="#cb80-39" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Avg. Treatment - Control"</span>)</span>
<span id="cb80-40"><a href="#cb80-40" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb80-41"><a href="#cb80-41" aria-hidden="true" tabindex="-1"></a>    ax.legend()</span>
<span id="cb80-42"><a href="#cb80-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-43"><a href="#cb80-43" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb80-44"><a href="#cb80-44" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy&gt;=1.26.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: matplotlib in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy&gt;=1.0.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler&gt;=0.10 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy&gt;=1.23 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging&gt;=20.0 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow&gt;=8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: statsmodels in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (0.14.4)
Requirement already satisfied: numpy&lt;3,&gt;=1.22.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,&gt;=1.8 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,&gt;=1.4 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy&gt;=0.5.6 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging&gt;=21.3 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (2025.2)
Requirement already satisfied: six&gt;=1.5 in c:\users\shruthi suresh\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas!=2.1.0,&gt;=1.4-&gt;statsmodels) (1.17.0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
[notice] A new release of pip is available: 24.3.1 -&gt; 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-14-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Conclusion:</p>
<p>These histograms show that as sample size increases, the sampling distribution becomes narrower and more normally distributed. At small sizes, zero lies in the center, suggesting no effect. At larger sizes (e.g., 1000), zero lies in the tail, and the distribution centers around the true treatment effect of 0.004, making the effect statistically detectable.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>